coverage:
  precision: 2
  round: down
  range: 50...80

  status:
    changes: false
    patch: true
    project: true

  ignore:
    # Ignore tests
    - "**/tests/.*"

    # Ignore `Exception` instances
    - "**/*Exception.java"

comment: false
