language: java

jdk:
  - oraclejdk8

env:
  global:
    JAVA_OPTS="-Xms256m -Xmx2g"

branches:
  only:
    - master

script:
  - mvn install

after_success:
  - bash <(curl -s https://codecov.io/bash)
