language: java

jdk:
  - oraclejdk8

env:
  global:
    - JAVA_OPTS="-Xms256m -Xmx2g"
    - secure: Mc7Pm9YGZiw3jr2NKBtIVozgC+iyrJ6F7V3UvpGPWQgn/IbJ6AM5YBSwvOk2P+jZI9k1vIgsrWIIKfu/1NYoJ5MC1mk94942ZNC+DJW1n+thgJ84xyLc4wXD8sYCdofWGcSrLYNZQpXkpbSuL8gVYk4iMQ8tI+jIoxRye1fgfYiBle2W3Pt/e4g0OGD339+ghSoKgBduM91elZmqFvf25CXYPcPtqZaXapmor9wBZyf8j7HLZsXLg2paA0Owpbn+WSdzFxKTvT3vn7ZY/iB6O80KYZTM/CcpzONdEEQUkMGc2bKfOVQ1lgqCbZyjbSyp8eTA43m949o+WOujhYQxqfZkg/1FPB5urIf+VF4o+hFFF/zZ8bJ6zPvD8MA7E4i3/LpNP7uNVndv6p8ijfm6fbuNe2MaK19yUQqMbriFlY6KfVy+o0yrc9InNoEFP+cbRMIoTVY/wIL5OIf06AE1RG7hNW7/jd8Nh4yuGLCgL87QybTxu37Jeho/K1XHZ2y7xi+6B3vbajvRpUgvyks/C0nnrpip5cnwS89XhEb/dj7rPvanfRiUUmoWxJKKEYut257SkP8AMxgUwc4TJb+GAsT7EyruToFsft4zzAXvejd6HM1QjAcq/96BbY8f6n+LnAHyKmwJbbLis0SxlmFMeyCeCJwcXmqzN7Axd/76gR4=

branches:
  only:
    - master

script:

# Build with code coverage
  - mvn -B jacoco:prepare-agent install jacoco:report-aggregate

after_success:

# Publish code coverage on CodeCov
  - bash <(curl -s https://codecov.io/bash)

# Build & publish javadoc on Github (gh-pages)
  - mvn -B -q javadoc:javadoc javadoc:aggregate
  - bash .script/publish_javadoc.sh

notifications:
  slack:
    secure: PRRla0SVB0vDVLgZOspKr+FxdlIB6t7FR4ewZLuDHvtUO5tySyrplFbf5Zfqujs3g2mYrk+7ZOBPUxHAY5mPEkjqi5nM2F0b9+xHdX3g+YIWW7qMntJ7ySWKatrKffewLQcJkYvJmiI56IuT/qgJa6dyFAgn+FI3hcvXv9zZtKYKXLJ0l5z8xL7akJz/woiLrlBcVxV8IO4nUWD8GLc/JURiNMeuZjeKUP+C1FHQlkQjLrqStfrpWnAmhZFfJYlEl7u4ElU36xdNmKwJ9VnTJUaB+y9mxAmsDhbsCzyta06/7xSVG7jULEhYC3phvLdE77TEqHnJIodqcQFWbcaxRzfjEWdBVjwaJLWoHGFCf9UahTlZzxIYXOs3s6PsZStL496+iPoVVoXt1N+vJ6mme962R1hhZ13Vzwu41/hjsAzQ+E68yM45DyCkG3Z3NQdoE1bxORZwiMhIz52DziVkOMNN2vymMVnIlpky4ky6XRBunidHKnnwgqzrPbxjgOVS3Lx/1zELeiHRNN1QLyKmoIezDL3LW6hjnxuZ6bf4hC/UXu0ZTWWK6L5jXMgXzCY8acUDO4Pka4ZK1guDM15HEzosxqfKp7PMT470a1Pc085x5j41Wzf7P6sYBrwHo4Hj9/EBFiYNiOFI51G/ilu37AO68OUuOEaamfUhh7AIeDo=
    on_success: always
    on_failure: always