language: java

jdk:
  - oraclejdk8

env:
  global:
    JAVA_OPTS="-Xms256m -Xmx1g"

branches:
  only:
    - master

install: true

script:
  - mvn install

after_success:
  - mvn -f plugins/eclipse verify
