language: java
os:
- linux
jdk:
- oraclejdk8
env:
  global:
  - JAVA_OPTS="-Xms256m -Xmx2g"
  - secure: Mc7Pm9YGZiw3jr2NKBtIVozgC+iyrJ6F7V3UvpGPWQgn/IbJ6AM5YBSwvOk2P+jZI9k1vIgsrWIIKfu/1NYoJ5MC1mk94942ZNC+DJW1n+thgJ84xyLc4wXD8sYCdofWGcSrLYNZQpXkpbSuL8gVYk4iMQ8tI+jIoxRye1fgfYiBle2W3Pt/e4g0OGD339+ghSoKgBduM91elZmqFvf25CXYPcPtqZaXapmor9wBZyf8j7HLZsXLg2paA0Owpbn+WSdzFxKTvT3vn7ZY/iB6O80KYZTM/CcpzONdEEQUkMGc2bKfOVQ1lgqCbZyjbSyp8eTA43m949o+WOujhYQxqfZkg/1FPB5urIf+VF4o+hFFF/zZ8bJ6zPvD8MA7E4i3/LpNP7uNVndv6p8ijfm6fbuNe2MaK19yUQqMbriFlY6KfVy+o0yrc9InNoEFP+cbRMIoTVY/wIL5OIf06AE1RG7hNW7/jd8Nh4yuGLCgL87QybTxu37Jeho/K1XHZ2y7xi+6B3vbajvRpUgvyks/C0nnrpip5cnwS89XhEb/dj7rPvanfRiUUmoWxJKKEYut257SkP8AMxgUwc4TJb+GAsT7EyruToFsft4zzAXvejd6HM1QjAcq/96BbY8f6n+LnAHyKmwJbbLis0SxlmFMeyCeCJwcXmqzN7Axd/76gR4=
  - secure: u1h+MPvaBg6OzbyJogZVmeGurbljMnGmYTTGhFv++a3I8J2AVCK3U3KrMThk69Xl51lMOjjZBj/VPSQj0NRIUyH3TMz1lxWNobDfgznlrMDl11dfj7FQMfFVLawjrs3KH2AnjyfhVeFq/bkpc40v72+cw9l8RQbziBlbIrJguX5nTMtRZaAby60xr7dCeIGyXRwSzcmbj1Q6xB7ZJxZzVFl0lG+kYIuImGmRG+lidIqroDKnAeZabVO89SDjJnZ/Zh9VcLmUh/Z83mm9EV2HG2EfmsCgbMFHqoEoPvHFUTBm8AyVvEEM0MQgUeLzMjAcnYHhAEzN0MCpzaQeItRj/TACALo6Wu/+S9KMvI3tRgjyjwxtMhK4kKq22wpAoROyYQobo+qyMrD0ZXcib31rmzTRz6jqDyHENAdK4jizIQUIdk44Fab22Ppkrwi6zoah6L4aQdW0uiUxYtFgw9OoTWY/tq/LpPMqF892cUBFfhYTEn699mrp1oQzomtbGzHGZlU82+XCOt6phQyYUX+7ZG1vBJzXOW4UevpcT8RvDKrPWUxTaaLe+7tLrpnZ/a9IQsogS9d1gxVp80WbyffILsdWBYZfTq9dyLum6/0siGFKNO02+9mtr5loJrPf7YyLD5aqhg3Zfu/88l1PmgSHu1Qdzz0I6ieA0kABSxgL1vU=
  - secure: nLTvpZjlPsnDVVSD5KHBtmuzL6rnZ4ndow9RTGyDSCFzj383Zn1VXQUICiDHqI9NloH4i3M71KdfYI+D6IHSz6BX3KHFPcSgjFnl/hGi4AQWg/YcuJK3m7FkDpEgVG6WFc5dSbcuueFv+a4Suyr0bNl8/1MN+z+L6KwyVxE0puCTD65hxmxSoZ3tvvhvKUf9xW5hQn2jJLCHqcpNcoeaTZR/SwboVZZe+m5rcI+OONjMxfwGUw17RA8d1mqRTUrZsd3XkT6gfTIwAbKk1TsudxxwLlvTCRDzfGHlPOMFTiqJFWSFDSLAzr/T2BpSLcVBY82beUE6nPPzEA9Ir3HYhOdVmR5FAxXiMk90VihnRwSOuxQQad1cnaOue7vpiP/tLsPM7wKjtd+lK3UyBmOuZr6iGP+8hkvuLuy2RECd6xclVKwMOeKfD3/0WSS1+RjBlEPQJ9gpbQAl9cyGDM2wAJhlQlo/J5npDov1utWMJ2Rzf6zmbzAeR2XgAlBmES5av2hF3sA8mFOwfqJsjw22kb79FazFp13DkpLNb/5PgTpY9sxb112DYKBglHwfxSbsCGPOxK4l1PoquEFUbvyPCn0CRs3G+7bndHi/oJT1FUvrw324Ir0X5ZDgti6EeGsnQt0KRmmGSaDFDleaEcilwUWZ3qqBHtBWpJEUk83s0eU=
branches:
  only:
  - master
script:
- mvn -B jacoco:prepare-agent install jacoco:report-aggregate
after_success:
- bash <(curl -s https://codecov.io/bash)
- bash .util/publish_javadoc.sh
- bash .util/publish_snapshot.sh
- bash .util/publish_eclipse.sh
notifications:
  slack:
    rooms:
      secure: I+soWCTe4u34GgD8069hEcSswPYPuKDjxjbM0/W5UsjBcog+G+9WfMM/NdXpi6MFKg7FnSdudTH34yLLoqYDVkDOqIZ+o/UG/jaTjHtqZeoJg5aQAXWVl0EVBfrPTltCwdDsrIwIuPJRk2RV5/0x4/Hp7KPtWfiRsweiu/0DQ4Zh0QbLMOgoXWKymU8g4x17ruJnJ8+1M//OCAfSZouJVga5U/RX1nPhB5lJtya6p27Nf1kRLTIh9Jksyv1fRhJE5qDrZCL1Qah5WvWJLraTy4Fs1hnY8ACMQURq/0nx4C37MsAYR2jFoixm+oCIxJlYrMWh7/wKS7UrAzniieXAYitMX7SnUWaihgE+3FRnD8QliPb8UeBAh0CUDHUxzrD7Jslbt+DVk4MjXfYPRzWfWHEIBzzIIPGwN540bKlHcTl5TD0eoKIzBc1DOxCCrAHmL5CfIIr5hj2/b7ZwTUIpYrtupBSV8sFD3X449VdRz+pVkDKj7FEVpAZ1Ywylg52wa0/2hObvfG9SbrhqSQZvKkTyEs4kdNuCjqUYlILOiqdz0fNbW4M7qvskONt9h5BunV7KyQkrnwfUVW0yA0D9eEG339aYbLwmLeSrrxMUFngK/9U63JsGmPmUQGafiomvLog6KJ04lXDTEURM1N1lZCGuJ5uYbqIpnSm9QwpmnWA=
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository} %{result} in %{duration}
    on_success: always
    on_failure: always
    on_pull_requests: false
