language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

install: true

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xms256m -Xmx1g"
 - "echo $JAVA_OPTS"

script:
  - mvn install

after_success:
  - mvn -f plugins/eclipse verify
